- name: "Adding user to the system"
  user:
    name: "{{ item.1 }}"
    groups: "{{ item.0.group }}"
    shell: /bin/bash

- name: "Check that {{ role_path }}/files/users/{{ item.1 }} is exist"
  local_action: "stat path={{ role_path }}/files/users/{{ item.1 }}.yml"
  register: user_config_exist

- name: "Set authorized key for {{ item.1 }}"
  authorized_key:
    user: "{{ item.1 }}"
    state: present
    key: "{{ lookup('file', 'files/users/' + item.1 + '.yml') | from_yaml | json_query('[*].key') | replace(\"[\",'') | replace(\"]\",'') | replace(\"'\",'') }}"
  when: user_config_exist.stat.exists == true and "lookup('file', 'files/users/' + item.1 + '.yml') | from_yaml | json_query('[*].key') | replace(\"[\",'') | replace(\"]\",'') | replace(\"'\",'')" and not ansible_check_mode
